### PR TITLE
chore(deps): use go 1.16

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by six-ddc** [comment]
Why do you need to upgrade to v1.16? This change will prevent the project from compiling in lower versions.

**Comment by chenrui333** [comment]
> Why do you need to upgrade to v1.16? This change will prevent the project from compiling in lower versions.

- go1.16 is using `go modules` by default
- maintain build go and runtime go version consistencies.
- as CLI app, you dont need to have lower go version for the build

**Comment by wweir** [comment]
You can use the `embd` feature for `jq` and `echart`.

**Comment by six-ddc** [comment]
LGTM, It's well worth upgrading for `embed` feature. thanks.

**Pull request merged**
