### PR TITLE
feat: default to POST instead of GET when body is given

### PR DESCRIPTION
**Pull request by FlorianLoch**
I am not sure checking whether `method` has actually been set might be too much - using `GET` with a body probably never makes sense, so one could probably also set it to `POST` even if `GET` has been set explicitly? 🤔 

On the other hand, this also covers the case of a user explicitly using another, legit, method.

### CODE REVIEW

**Comment by FlorianLoch** [comment]
Closes #72.

**Comment by six-ddc** [comment]
Although it is not common for GET requests to have a request body, it should be considered permissible.

**Comment by six-ddc** [comment]
LGTM

**Comment by FlorianLoch** [comment]
> Although it is not common for GET requests to have a request body, it should be considered permissible.

Alright, then the currently suggested implementation should match that. Just double checked, should be fine.

Just noticed the help string of the `body` parameters was a little hard to read - added a commit suggesting an improvement. For ease of workflow I simply (ab)used this PR for it ;)

**Pull request merged**
